name: Flutter CI/CD

on:
  push:
    branches:
      - develop # develop 브랜치에 푸시될 때 실행
  pull_request:
    branches:
      - develop

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest # GitHub Actions가 실행될 환경

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Git 저장소의 코드를 가져옴

      - name: Setup Flutter
        uses: subosito/flutter-action@v3
        with:
          flutter-version: '3.29.0' # 사용할 Flutter 버전

      - name: Install dependencies
        run: flutter pub get # 패키지 의존성 설치

      # - name: Run tests
      #   run: flutter test # 테스트 자동 실행

      - name: Build APK
        run: flutter build apk --release # APK 빌드

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
